# Generated by Django 5.2.7 on 2025-10-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'New Comment'), ('like', 'Post Liked'), ('follow', 'New Follower'), ('bookmark', 'New Bookmark'), ('share', 'Post Shared')], default='like', max_length=20),
        ),
    ]
